[model]
epochs = 3
metrics = ["Accuracy"]
logdir = "gestures"
train_steps = 81
valid_steps = 20
reporttypes = ["ReportTypes.TOML", "ReportTypes.TENSORBOARD", "ReportTypes.MLFLOW"]
[model.optimizer_kwargs]
lr = 0.001
weight_decay = 1e-05

[model.scheduler_kwargs]
factor = 0.5
patience = 5

[model.earlystop_kwargs]
save = false
verbose = true
patience = 5
delta = 0.0


[types]
epochs = "int"
metrics = "list"
logdir = "WindowsPath"
train_steps = "int"
valid_steps = "int"
reporttypes = "list"
optimizer_kwargs = "dict"
scheduler_kwargs = "dict"
earlystop_kwargs = "dict"
